[package]
name = "gpui-pre-http-client-tls"
version = "0.3.8"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `http_client_tls` crate (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "http_client_tls"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
path = "src/http_client_tls.rs"
doctest = false
test = false
name = "http_client_tls"

[features]
test-support = []

[dependencies]
log = { workspace = true }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
webpki-roots = { workspace = true }

[lints]
workspace = true
