[package]
name = "gpui-pre-util"
version = "0.3.8"
publish = true
edition = { workspace = true }
license = "Apache-2.0"
description = "Zed's `gpui_util` crate (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "gpui_util"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
doctest = false
name = "gpui_util"

[features]

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
which = { workspace = true }

[lints]
workspace = true
