[package]
name = "gpui-pre-zlog"
version = "0.3.8"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `zlog` crate (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "zlog"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
path = "src/zlog.rs"
doctest = false
name = "zlog"

[features]
default = []

[dependencies]
collections = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
