[package]
name = "gpui-pre-macros"
version = "0.3.8"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Macros used by gpui (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "gpui_macros"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
path = "src/gpui_macros.rs"
proc-macro = true
doctest = true
test = false
name = "gpui_macros"

[features]
inspector = []

[dependencies]
heck = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
proc-macro-crate = "3"

[lints]
workspace = true
