[package]
name = "gpui-pre-ztracing-macro"
version = "0.3.8"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `ztracing_macro` crate (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "ztracing_macro"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
proc-macro = true
test = false
doctest = false
name = "ztracing_macro"

[features]
