[package]
name = "gpui-pre-reqwest-client"
version = "0.3.8"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `reqwest_client` crate (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "reqwest_client"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
path = "src/reqwest_client.rs"
doctest = false
name = "reqwest_client"

[features]
test-support = []

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http_client = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
regex = { workspace = true }
reqwest = { workspace = true }
gpui_util = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
http_client_tls = { workspace = true }

[lints]
workspace = true
