[package]
name = "gpui-pre-derive-refineable"
version = "0.3.8"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "A derive macro for creating refinement types in Rust (gpui-pre snapshot of zed@279fe07)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "derive_refineable"
zed-version = "0.1.0"
zed-rev = "279fe070bb389b79652e52065b2f001edcc0b11b"

[lib]
path = "src/derive_refineable.rs"
proc-macro = true
doctest = false
test = false
name = "derive_refineable"

[features]

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
